apiVersion: discovery.k8s.io/v1
kind: EndpointSlice
metadata:
  name: es-static
  namespace: infra
  labels:
    kubernetes.io/service-name: es
addressType: IPv4
ports:
  - name: http
    protocol: TCP
    port: 9200
endpoints:
  - addresses:
      - <INTERNAL_IP>
