apiVersion: discovery.k8s.io/v1
kind: EndpointSlice
metadata:
  name: kibana-static
  namespace: infra
  labels:
    kubernetes.io/service-name: kibana
addressType: IPv4
ports:
  - name: http
    protocol: TCP
    port: 5601
endpoints:
  - addresses:
      - <INTERNAL_IP>
