apiVersion: v1
kind: ConfigMap
metadata:
  name: filebeat-config
  namespace: observer
data:
  filebeat.yml: |
    filebeat.inputs:
      - type: filestream
        id: ingress-nginx-access

        prospector.scanner.symlinks: true

        paths:
          - /var/log/containers/*ingress-nginx-controller*.log

        parsers:
          - container: {}

        include_lines: ['time=']

        processors:
          - add_kubernetes_metadata:
              host: ${NODE_NAME}
              matchers:
                - logs_path:
                    logs_path: "/var/log/containers/"
          - add_fields:
              target: ''
              fields:
                env: homelab
                source: ingress-nginx

    output.elasticsearch:
      hosts: ["http://es.infra.svc.cluster.local:9200"]
      headers:
        Authorization: "ApiKey ${ES_API_KEY}"
      index: "ingress-access"
      pipeline: "ingress-access-pipeline"

    setup.template.enabled: false
    setup.ilm.enabled: false
