services:
  es:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.11.3
    container_name: es
    restart: unless-stopped
    environment:
      - node.name=es01
      - discovery.type=single-node
      - xpack.security.enabled=true
      - xpack.security.http.ssl.enabled=false
      - xpack.security.audit.enabled=true
      - xpack.security.audit.logfile.events.emit_request_body=false
      - ES_JAVA_OPTS=${ES_JAVA_OPTS}
    volumes:
      - es-data:/usr/share/elasticsearch/data
    ports:
      - "9200:9200"
    networks:
      - infra

  kibana:
    image: docker.elastic.co/kibana/kibana:8.11.3
    container_name: kibana
    restart: unless-stopped
    environment:      
      - SERVER_PUBLICBASEURL=${SERVER_PUBLICBASEURL}
      - ELASTICSEARCH_HOSTS=${ELASTICSEARCH_HOSTS}
      - ELASTICSEARCH_USERNAME=${ELASTICSEARCH_USERNAME}
      - ELASTICSEARCH_PASSWORD=${ELASTICSEARCH_PASSWORD}
    ports:
      - "5601:5601"
    depends_on:
      - es
    networks:
      - infra

volumes:
  es-data:

networks:
  infra:
    external: true
